// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWfoJMV_M7xuun6Y1z_fHfjeffTLeKzHA',
    appId: '1:405917008307:web:12790f1a3700ca53214bc6',
    messagingSenderId: '405917008307',
    projectId: 'base-de-datos-acbc4',
    authDomain: 'base-de-datos-acbc4.firebaseapp.com',
    databaseURL: 'https://base-de-datos-acbc4-default-rtdb.firebaseio.com',
    storageBucket: 'base-de-datos-acbc4.appspot.com',
    measurementId: 'G-RGL3SETH0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDs0SdgnjMH2qWYyFwzpKL3Fvc-7JwgEU',
    appId: '1:405917008307:android:2f4f1ae5291d272c214bc6',
    messagingSenderId: '405917008307',
    projectId: 'base-de-datos-acbc4',
    databaseURL: 'https://base-de-datos-acbc4-default-rtdb.firebaseio.com',
    storageBucket: 'base-de-datos-acbc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4k4PgR2cjNQ7lEaP_tDBjwNTcddLQoBg',
    appId: '1:405917008307:ios:9c488e44d4658737214bc6',
    messagingSenderId: '405917008307',
    projectId: 'base-de-datos-acbc4',
    databaseURL: 'https://base-de-datos-acbc4-default-rtdb.firebaseio.com',
    storageBucket: 'base-de-datos-acbc4.appspot.com',
    iosClientId: '405917008307-ds44jaa4685sejs96tm2ir5k74jigmsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4k4PgR2cjNQ7lEaP_tDBjwNTcddLQoBg',
    appId: '1:405917008307:ios:9c488e44d4658737214bc6',
    messagingSenderId: '405917008307',
    projectId: 'base-de-datos-acbc4',
    databaseURL: 'https://base-de-datos-acbc4-default-rtdb.firebaseio.com',
    storageBucket: 'base-de-datos-acbc4.appspot.com',
    iosClientId: '405917008307-ds44jaa4685sejs96tm2ir5k74jigmsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWfoJMV_M7xuun6Y1z_fHfjeffTLeKzHA',
    appId: '1:405917008307:web:fe02f21de672b375214bc6',
    messagingSenderId: '405917008307',
    projectId: 'base-de-datos-acbc4',
    authDomain: 'base-de-datos-acbc4.firebaseapp.com',
    databaseURL: 'https://base-de-datos-acbc4-default-rtdb.firebaseio.com',
    storageBucket: 'base-de-datos-acbc4.appspot.com',
    measurementId: 'G-QQZM5ZHDJK',
  );
}
